image: bitpoke/devcontainer:latest

tasks:
  - name: Docker Compose
    before: |
      test -f docker-compose.override.yaml || cp .devcontainer/docker-compose.override.yaml ./
      echo "UID=$(id -u)" >> .env
      echo "GID=$(id -g)" >> .env
    init: docker-compose pull
    command: docker-compose up -d ; docker-compose logs -f wordpress

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore

vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - johnbillion.vscode-wordpress-hooks
    - ms-azuretools.vscode-docker
    - mtxr.sqltools
    - mtxr.sqltools-driver-mysql
