version: '3.3'

services:
  wordpress:
    user: "${UID:-33}:${GID:-33}"
    tmpfs:
      - /usr/local/docker/etc:uid=${UID:-33},gid=${GID:-33}
      - /var/run:uid=${UID:-33},gid=${GID:-33}
    depends_on:
      - db
      - memcached
    build: .
    volumes:
      - ./config:/app/config
      - ./wp-content:/app/web/wp-content
    restart: always
    environment:
      DB_HOST: db:3306
      DB_USER: wordpress
      DB_PASSWORD: not-so-secure
      DB_NAME: wordpress
      MEMCACHED_HOST: memcached:11211
      WP_ENV: development
      NGINX_ACCESS_LOG: /dev/stdout # enable nginx access log
      STATS_ENABLED: "true" # allow access to paths like /-/php-info
      STATS_WHITELIST_CIDR: 0.0.0.0/0 # allow access to stats from everywhere, since we are in development mode
  db:
    image: percona:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: not-so-secure
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: not-so-secure

  memcached:
    image: memcached:1.5

volumes:
    db_data: {}
