services:
  db:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 3306:3306
    volumes:
      - ${WORKSPACE_FOLDER:-/workspace}:${WORKSPACE_FOLDER:-/workspace}
  wordpress:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    volumes:
      - ${WORKSPACE_FOLDER:-/workspace}:${WORKSPACE_FOLDER:-/workspace}
    environment:
      - CODESPACES
      - CODESPACE_NAME
      - GITPOD_WORKSPACE_ID
      - GITPOD_WORKSPACE_URL
      - GITPOD_REPO_ROOT
      - GITPOD_WORKSPACE_CLUSTER_HOST
